Project feature
jstloyal/private-events pull request #1
Opened 2020-06-29 11:44 UTC by jstloyal

Building a private event app

2020-06-29 18:25 UTC, mcrd25 requested changes
# Changes Required :mag: 

Hi @jstloyal :wave: 

Good attempt so far! We are getting there! :smile: 

There are a few issues to address:
#### Required Changes
- Address all review comments not listed as [OPTIONAL]
- Ensure no application logic in helpers
- Remove ALL commented-out code
- Add unit and integration tests (they are missing) [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) and [this screesnhot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from pathwright lists it as a requirement
- Your app was unable to be tested because of this issue
![Screenshot from 2020-06-29 14-00-31](https://user-images.githubusercontent.com/31193823/86041700-0be6aa80-ba14-11ea-8a0a-c67d33121e33.png)


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-29 18:25 UTC, mcrd25 commented on app/controllers/application_controller.rb
> +  include SessionsHelper
If you have SessionsHelper included in Application Controller it probably means that you probably have code in SessionsHelper that is meant for Controller.

2020-06-29 18:25 UTC, mcrd25 commented on app/controllers/sessions_controller.rb
> +    # empty
Is this necessary? [OPTIONAL]

2020-06-29 18:25 UTC, mcrd25 commented on app/helpers/sessions_helper.rb
> +  end
You seem to have application logic inside of your helpers. Helper methods ought to be view specific; the fact that you have to import the helpers in Application Controller for you to have access to those methods in controllers while you do not even use it in your views reiterates this. The views on the other hand, automatically have access to helper methods. 
So, what you can do is add all methods which are not views specific to your application controller directly. What you can also do if your method list gets long, you may use concerns or a lib folder to separate methods by function, etc.

Basically helpers = views, controller = controller. Why write methods in helpers only to have to include it in controller after. Helpers are automatically accessible in views. there is a reason helpers are outside the context of the controller folder. You can, however, use concerns in your controllers.

Read [this article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and [this article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for a clearer explanation. 🙂 

**Not sure this was a requirement?** Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/).

2020-06-29 18:25 UTC, mcrd25 commented on app/helpers/sessions_helper.rb
> +    @current_user ||= User.find(user_id) if (User.id = session[:id])
This is application logic. There should be no application logic in helpers. (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...)

See [this screenshpt](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright

2020-06-29 18:25 UTC, mcrd25 commented on app/controllers/users_controller.rb
> +    # cookies[:id] = @user.id
You ought to remove commented out code.
It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history.
Ass you can see from [this screesnhot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from pathwright. This is a requirement to address all occurrences of commented out code.

2020-07-01 18:25 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Most of your unit tests suite is failing.
- [x] Integration tests should be included.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-03 15:58 UTC, shshamim63 requested changes
## :recycle:  Required Changes :recycle: 
___
Hi @jstloyal :wave:
The design of the page is neat and clean. Mostly it is simple. But I faced some issues.
- I tried to open your project and was not able to see the view that you added on your screenshot, I could not find any attend event button. 
![image](https://user-images.githubusercontent.com/38625956/86484201-85193100-bd77-11ea-80fe-f9d6a2efbb54.png)
- As a logged in user I should not be asked to sign in again
![image](https://user-images.githubusercontent.com/38625956/86484170-6fa40700-bd77-11ea-9957-e8b4890acb3e.png)
- To confirm that I am at the right branch
![image](https://user-images.githubusercontent.com/38625956/86484264-a5e18680-bd77-11ea-9162-c1cba12063d1.png)
- Your seed file also needs some correction, check out the comment.

Are you sure the last commit contains all of the latest tasks? Please double-check it. And send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-03 15:58 UTC, shshamim63 commented on db/seeds.rb
> +akanmu.created_events.create!(name: "sandbox party", place: "my sandbox", date: 1.month.from_now, description: "dont forget your toys (to not use mine again)")
You don't have any place column in your event table. So you should not be able to set up the database properly. Instead of place, it should be the location.

2020-07-03 17:05 UTC, jstloyal commented on db/seeds.rb
> +akanmu.created_events.create!(name: "sandbox party", place: "my sandbox", date: 1.month.from_now, description: "dont forget your toys (to not use mine again)")
You are not asked to sign in, it says: Signed in as 
which is a past tense of sign in but I can change it anyway.
Thank you for the review, really appreciate.

2020-07-06 14:30 UTC, shshamim63 requested changes
## :recycle: Required Changes :recycle: 
___
Hi @jstloyal :wave: 
Nice :clap: You have fixed the error in the seed and I can see a button to attend the event now. But that is not functional. Let's have a look at them.
___
### :spades: Mandatory Changes :spades: 
___
- I could not find users show page where a user can see created and events that the user is attending to separated in past and upcoming
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)
- I tried to attend an event but nothing happened.
- The event's show page displays the list of attendants ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
### :clubs: Optional Changes :clubs: 
___
-  https://github.com/jstloyal/private-events/pull/1#discussion_r449661813
I am totally aware of the tense. And tense is not the issue that I am mentioning. I am logged in as demouser. If I click on it, it is taking me to the sign in page again. My question is, if I am a logged-in user why do I need to sign-in again?
![image](https://user-images.githubusercontent.com/38625956/86603067-57292c00-bfc5-11ea-8601-b40d814413ca.png)
![image](https://user-images.githubusercontent.com/38625956/86603353-b5560f00-bfc5-11ea-8642-20fe8bcd38ff.png)
___
##### Please Fix the above-mentioned issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-08 13:14 UTC, stratospherique requested changes
### Great progress @jstloyal :clap: :clap: However, some changes need to be applied in order to get approval for this project. Check :arrow_down: 

- When trying your app I notices the following issues:
  - I can't create an event
![image](https://user-images.githubusercontent.com/26124023/86922046-febc7080-c123-11ea-9985-9726bdade530.png)
  - I can't edit an event
![image](https://user-images.githubusercontent.com/26124023/86922113-17c52180-c124-11ea-8635-2bdd7f384099.png)

  - I can't attend an event and it doesn't show who attended the event.
- **[REQUIRED]** Most of these errors are caused by the wrong usage of ActiveRecord methods :mag: kindly fix them

- **[REQUIRED]** User login and signup views should only be accessible by a non logged in user.

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-07-08 19:11 UTC, uryelah commented
Hi **Loyalty Adetayo**, I'm Sarah your reviewer for this PR 👩‍🚀 

The basic required functionalities of the project are working, so I'll approve it.
But make sure to research on how to perform updates with rails. You have an #edit action but no #update action at all, that would be like having a #new action and no #create one.

Error when trying to edit event:

![Screenshot_2020-07-08 Action Controller Exception caught](https://user-images.githubusercontent.com/16193212/86960288-ad1ce180-c135-11ea-9162-f5fdc85a9877.png)


If you want to keep the edit button make sure it's working 😉 too.

Another optional change would be changing the text of the button for the edit form, it should not be the same as for the create form.

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-09 12:35 UTC, merged